name: desafio-um

on:
  workflow_dispatch
    inputs:
      nome-imagem: 
        description: "Nome da imagem Docker (ex: ubuntu:latest, alpine:latest)"
        required: true
        default: 'alpine:latest'\
        type: string

jobs: 
  exercicio-um:
    runs-on: ubuntu-latest
    steps:
      - name: Baixa imagem
        run: docker pull ${{ inputs.nome-imagem}}
     
      - name: Verifica imagens
        run: docker images
        
        