name: desafio-um

on:
  workflow_dispatch

jobs: 
  exercicio-um:
    runs-on: ubuntu-latest
    steps:
      - name: Baixa imagem
        run: docker pull alpine:latest
     
      - name: Verifica imagens
        run: docker images
        
        