name: Vendo arquivos compartilhados entre Steps

on:
  push:
    branches:
      - main

jobs: 
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Confere versao do ubuntu
        run: cat /etc/os-release
     
      - name: Exibir uma mensagem
        run: echo "Estou fazendo o curso de GitHub Actions da Linuxtips" > mensagem.txt
        
      
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Acessa arquivo mensagem
        run: ls -lha

      - name: Acessa arquivo mensagem
        run: cat mensagem.txt